services:
  fptn-server:
    restart: unless-stopped
    image: fptnvpn/fptn-vpn-server:latest
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      - HTTPS_PORT=${HTTPS_PORT}
      - $$DISABLE_BITTORRENT=${DISABLE_BITTORRENT}
      - ENABLE_DETECT_PROBING=${ENABLE_DETECT_PROBING}
    ports:
      - ${HTTPS_PORT}:443
    volumes:
      - ./configs:/etc/fptn/:r
      - ./logs:/var/log/fptn_bot:rw
    command: >-
      bash -c "
        dnsmasq --no-daemon &
        sleep 2;
        export INTERFACE=$$(ip -o -4 route show to default | awk '{print $$5}');
        echo "INTERFACE=$$INTERFACE" >&2;
        /usr/bin/fptn-server --server-key=/etc/fptn/server.key --server-crt=/etc/fptn/server.crt --server-pub=/etc/fptn/server.pub --out-network-interface=$$INTERFACE --server-port=443 --tun-interface-name=fptn0 --disable-bittorrent=$$DISABLE_BITTORRENT --enable-detect-probing=$$ENABLE_DETECT_PROBING
      "
