{
 "title": "FPTN Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active VPN sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fptn_active_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sessions history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "fptn_active_sessions", "legendFormat": "USERS" }
   ]
  },
  {
   "title": "User outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(fptn_user_outgoing_traffic_bytes[$__rate_interval])*8) ",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "User incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(fptn_user_incoming_traffic_bytes[$__rate_interval])*8)",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Total  Outgoing Traffic for 1h",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(fptn_user_outgoing_traffic_bytes[$__rate_interval]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Total Incoming Traffic for the  1h",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(fptn_user_incoming_traffic_bytes[1h]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  { "title": "Additional info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "User outgoing Traffic Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(fptn_user_outgoing_traffic_bytes[$__rate_interval])*8) by (username)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(fptn_user_outgoing_traffic_bytes[$__rate_interval])*8) ",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "User Incoming Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(fptn_user_incoming_traffic_bytes[$__rate_interval])*8) by (username)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(fptn_user_incoming_traffic_bytes[$__rate_interval])*8) ",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Outgoing traffic by user for 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(fptn_user_outgoing_traffic_bytes[$__rate_interval])) by (username)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "incoming traffic by user for 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(fptn_user_incoming_traffic_bytes[$__rate_interval])) by (username)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}